version: '3'
services:

  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:8.1.4
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=5
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    depends_on:
      - elasticsearch
    volumes:
      - ./application.yml:/usr/local/zeebe/config/application.yml
    networks:
      - zeebe_network

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.5.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - ES_JAVA_OPTS=-Xmx750m -Xms750m
    networks:
      - zeebe_network

  operate:
    container_name: operate
    image: camunda/operate:latest
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
      - elasticsearch
    networks:
      - zeebe_network
    volumes:
      - ./operate-application.yml:/usr/local/operate/config/application.yml

networks:
  zeebe_network:
    driver: bridge
