zeebe:
  client:
    security:
      plaintext: true
    broker:
      gateway-address: localhost:26500
    worker:
      max-jobs-active: 32
      threads: ${MAX_ZEEBE_THREADS:16}

springdoc:
  swagger-ui:
    enabled: ${ENABLE_SWAGGER:true}
    path: /swagger-ui
