### Create instance of process-with-reusable-call-activity.bpmn
< {%
    function getNextKey() {
        let previous = client.global.get('key1')
        if (previous == null) {
            return "1"
        } else {
            let newKey = parseInt(previous)
            return (++newKey).toFixed(0)
        }
    }
    client.global.set('key1', getNextKey())
%}
POST http://localhost:8080/processes
Content-Type: application/json

{
  "bpmnProcessId": "process-with-reusable-call-activity",
  "vars": {
    "key": "{{key1}}",
    "var1": "TWO"
  }
}

### Send message 'MsgCreateNewSimpleProcess'
POST http://localhost:8080/messages
Content-Type: application/json

{
  "msgName": "MsgCreateNewSimpleProcess",
  "correlationKey": "{{key1}}",
  "vars": {
    "var1": "ONE"
  }
}

### Send message 'MsgSimpleProcessEvent'
POST http://localhost:8080/messages
Content-Type: application/json

{
  "msgName": "MsgSimpleProcessEvent",
  "correlationKey": "{{key1}}"
}

### Send message 'MsgCompleteMainProcess'
POST http://localhost:8080/messages
Content-Type: application/json

{
  "msgName": "MsgCompleteMainProcess",
  "correlationKey": "{{key1}}"
}
