### Create instance of process-with-multi-instance-call-activity.bpmn
POST http://localhost:8080/processes
Content-Type: application/json

{
  "bpmnProcessId": "process-with-multi-instance-call-activity",
  "vars": {
    "key": "04",
    "subprocess_collection": [
      {
        "registration_message": "TWO",
        "key": "04-1"
      },
      {
        "registration_message": "TWO",
        "key": "04-2"
      }
    ]
  }
}

### Send message 'MsgSimpleProcessEvent'
POST http://localhost:8080/messages
Content-Type: application/json

{
  "msgName": "MsgSimpleProcessEvent",
  "correlationKey": "04-1",
  "vars": {
    "simple_process_var": "simple process 04-1 var"
  }
}

