### Create instance of simple-process.bpmn
< {%
    function getNextKey() {
        let previous = client.global.get('key')
        if (previous == null) {
            return "1"
        } else {
            let newKey = parseInt(previous)
            return (++newKey).toFixed(0)
        }
    }
    client.global.set('key', getNextKey())
%}
POST http://localhost:8981/processes
Content-Type: application/json

{
  "bpmnProcessId": "simple-process",
  "vars": {
    "registration_message": "ONE",
    "key": "{{key}}"
  }
}

### Send message 'MsgSimpleProcessEvent'
POST http://localhost:8080/messages
Content-Type: application/json

{
  "msgName": "MsgSimpleProcessEvent",
  "correlationKey": "{{key}}",
  "vars": {
    "needToStartAgain": false,
    "additionalProp1": {"name": "name"}
  }
}
