### Send message 'CHECK_SLA'
POST http://localhost:8080/messages
Content-Type: application/json

{
  "msgName": "CHECK_SLA",
  "correlationKey": "SLA1_{{processId1}}",
  "vars": {
    "completed": true
  }
}

### Send message 'CHANGE_SLA'
POST http://localhost:8080/messages
Content-Type: application/json

{
  "msgName": "CHANGE_SLA",
  "correlationKey": "SLA1_{{processId1}}"
}

