version: "3"

networks:
  zeebe_network:
    driver: bridge

services:
  gateway:
    container_name: gateway
    image: camunda/zeebe:8.0.3
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_HAZELCAST_REMOTE_ADDRESS=hazelcast:5701
      - ZEEBE_STANDALONE_GATEWAY=true
      - ZEEBE_GATEWAY_NETWORK_HOST=0.0.0.0
      - ZEEBE_GATEWAY_NETWORK_PORT=26500
      - ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT=node0:26502
      - ZEEBE_GATEWAY_CLUSTER_PORT=26502
      - ZEEBE_GATEWAY_CLUSTER_HOST=gateway
#      - ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH=exporters/zeebe-hazelcast-exporter.jar
#      - ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME=io.zeebe.hazelcast.exporter.HazelcastExporter
    ports:
      - "26500:26500"
    volumes:
      - ./exporter/zeebe-hazelcast-exporter-1.2.1-SNAPSHOT-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network

  node0:
    container_name: zeebe_broker_1
    image: camunda/zeebe:8.0.3
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_HAZELCAST_REMOTE_ADDRESS=hazelcast:5701
      - ZEEBE_BROKER_CLUSTER_NODEID=0
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=10
#      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
#      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
#      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502,node1:26502,node2:26502
#      - ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH=exporters/zeebe-hazelcast-exporter.jar
#      - ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME=io.zeebe.hazelcast.exporter.HazelcastExporter
    ports:
      - "9600:9600"
    volumes:
      - ./exporter/zeebe-hazelcast-exporter-1.2.1-SNAPSHOT-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network

  node1:
    container_name: zeebe_broker_2
    image: camunda/zeebe:8.0.3
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_HAZELCAST_REMOTE_ADDRESS=hazelcast:5701
      - ZEEBE_BROKER_CLUSTER_NODEID=1
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=10
#      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
#      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
#      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502,node1:26502,node2:26502
    volumes:
      - ./exporter/zeebe-hazelcast-exporter-1.2.1-SNAPSHOT-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
    depends_on:
      - node0

  hazelcast:
    container_name: hazelcast
    image: hazelcast/hazelcast:5.1.2
    ports:
      - "5701:5701"
    networks:
      - zeebe_network

  simple-monitor-in-memory:
    container_name: zeebe-simple-monitor-in-memory
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.3.0
    environment:
      - zeebe.client.broker.gateway-address=gateway:26500
      - zeebe.client.worker.hazelcast.connection=hazelcast:5701
    ports:
      - "8082:8082"
    networks:
      - zeebe_network
    profiles:
      - in-memory

#  simple-monitor-postgres:
#    container_name: zeebe-simple-monitor-postgres
#    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.3.0
#    environment:
#      - zeebe.client.broker.gateway-address=gateway:26500
#      - zeebe.client.worker.hazelcast.connection=hazelcast:5701
#      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
#      - spring.datasource.username=postgres
#      - spring.datasource.password=zeebe
#      - spring.datasource.driverClassName=org.postgresql.Driver
#      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#    ports:
#      - "8082:8082"
#    depends_on:
#      - zeebe
#      - postgres
#    networks:
#      - zeebe_network
#
#  postgres:
#    image: postgres:13.3
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: zeebe
#    ports:
#      - "5432:5432"
#    networks:
#      - zeebe_network
