version: "3"

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:8.0.3
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./exporter/zeebe-hazelcast-exporter-1.2.1-SNAPSHOT-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network

  simple-monitor-in-memory:
    container_name: zeebe-simple-monitor-in-memory
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.3.0
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
    profiles:
      - in-memory

#  simple-monitor-postgres:
#    container_name: zeebe-simple-monitor-postgres
#    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.3.0
#    environment:
#      - zeebe.client.broker.gateway-address=gateway:26500
#      - zeebe.client.worker.hazelcast.connection=hazelcast:5701
#      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
#      - spring.datasource.username=postgres
#      - spring.datasource.password=zeebe
#      - spring.datasource.driverClassName=org.postgresql.Driver
#      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#    ports:
#      - "8082:8082"
#    depends_on:
#      - zeebe
#      - postgres
#    networks:
#      - zeebe_network
#    profiles:
#      - postgres
#
#  postgres:
#    image: postgres:12.2
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: zeebe
#    ports:
#      - "5432:5432"
#    networks:
#      - zeebe_network
#    profiles:
#      - postgres

networks:
  zeebe_network:
    driver: bridge
