### Cancel instance
POST http://localhost:8081/processes/11258999068466982/cancel

### Update job retries
POST http://localhost:8081/jobs/11258999068507741/retries
Content-Type: application/json

{
  "retries": 3
}


### Resolve incident
POST http://localhost:8081/incidents/11258999068507747/resolve


### Delete process definition
DELETE http://localhost:8081/process-definitions/2251799813685249


### Deploy process definition
POST http://localhost:8081/process-definitions
Content-Type: application/json

{
  "fileName": "D:\\Projects\\camunda8-demo\\src\\main\\resources\\bpmn\\process-with-embedded-subprocess.bpmn"
}


### Get topology
GET http://localhost:8081/topology


### Average execution-time
GET http://localhost:8081/execution-time/average

### Max execution-time
GET http://localhost:8081/execution-time/max

### Min execution-time
GET http://localhost:8081/execution-time/min

### Clear execution-time
DELETE http://localhost:8081/execution-time
